# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Vertical layout for all main elements
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")

        # Tab widget for different analysis types
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")

        # Extract tab
        self.tabExtract = QtWidgets.QWidget()
        self.tabExtract.setObjectName("tabExtract")
        self.tabWidget.addTab(self.tabExtract, "")
        
        # Registry tab
        self.tabRegistry = QtWidgets.QWidget()
        self.tabRegistry.setObjectName("tabRegistry")
        self.tabWidget.addTab(self.tabRegistry, "")
        
        # Logs tab
        self.tabLogs = QtWidgets.QWidget()
        self.tabLogs.setObjectName("tabLogs")
        self.tabWidget.addTab(self.tabLogs, "")
        
        # Network tab
        self.tabNetwork = QtWidgets.QWidget()
        self.tabNetwork.setObjectName("tabNetwork")
        self.tabWidget.addTab(self.tabNetwork, "")
        
        # Timestamp tab
        self.tabTimestamp = QtWidgets.QWidget()
        self.tabTimestamp.setObjectName("tabTimestamp")
        self.tabWidget.addTab(self.tabTimestamp, "")
        
        # Malware tab
        self.tabMalware = QtWidgets.QWidget()
        self.tabMalware.setObjectName("tabMalware")
        self.tabWidget.addTab(self.tabMalware, "")

        # Add the tab widget to the layout
        self.verticalLayout.addWidget(self.tabWidget)

        # Start Analysis Button
        self.pushButtonStartAnalysis = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonStartAnalysis.setObjectName("pushButtonStartAnalysis")
        self.verticalLayout.addWidget(self.pushButtonStartAnalysis)

        # Progress bar
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.verticalLayout.addWidget(self.progressBar)

        # Results display
        self.textBrowserResults = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowserResults.setObjectName("textBrowserResults")
        self.verticalLayout.addWidget(self.textBrowserResults)

        # Generate Report Button
        self.pushButtonGenerateReport = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonGenerateReport.setObjectName("pushButtonGenerateReport")
        self.verticalLayout.addWidget(self.pushButtonGenerateReport)

        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Forensic Analysis Tool"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabExtract), _translate("MainWindow", "Extract Files"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabRegistry), _translate("MainWindow", "Registry Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabLogs), _translate("MainWindow", "Logs Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabNetwork), _translate("MainWindow", "Network Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabTimestamp), _translate("MainWindow", "Timestamp Analysis"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabMalware), _translate("MainWindow", "Malware Scanning"))
        self.pushButtonStartAnalysis.setText(_translate("MainWindow", "Start Analysis"))
        self.pushButtonGenerateReport.setText(_translate("MainWindow", "Generate Report"))

